kind: Deployment
apiVersion: apps/v1
metadata:
  name: chis-core
  namespace: default
  labels:
    app: chis-core
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chis-core
  template:
    metadata:
      labels:
        app: chis-core
        role: rolling-update
        build_number: '<TAG>'
    spec:
      containers:
        - name: chis-core
          image: 'bakcovn/chis-core:latest'
      imagePullSecrets:
        - name: regcred
  strategy:
    type: RollingUpdate
