pipeline {

  environment {
    registry = "192.168.1.2:5000/vkhealth/sm"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git 'https://gitlab.com/vkhealth/schedule-management.git'
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }

    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( "" ) {
            dockerImage.push()
          }
        }
      }
    }

    stage('Deploy App') {
      steps {
        script {
          kubernetesDeploy(configs: "scheduleManagement.yaml", kubeconfigId: "mykubeconfig")
        }
      }
    }

  }

}